name: Build ReShade Addon

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, Win32]
        include:
          - arch: x64
            cmake_arch: x64
            artifact_name: swapchain_override_addon64
          - arch: Win32
            cmake_arch: Win32
            artifact_name: swapchain_override_addon32

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v2

    - name: Configure CMake
      run: |
        cmake -B build -G "Visual Studio 17 2022" -A ${{ matrix.cmake_arch }}

    - name: Build
      run: |
        cmake --build build --config Release

    - name: List build output
      run: |
        dir build\Release

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: |
          build/Release/${{ matrix.artifact_name }}.dll
          build/Release/${{ matrix.artifact_name }}.addon
        if-no-files-found: error
